# Generated by Django 5.0.1 on 2024-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerhub', '0002_rename_university_college_lawyer_university_college_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='administrator',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='administrator',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='administrator',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='administrator',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='administrator',
            name='role',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='administrator',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='role',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
