# Generated by Django 5.0.1 on 2024-01-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerhub', '0003_delete_user_administrator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
