# Generated by Django 5.0.1 on 2024-01-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerhub', '0004_alter_client_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
