# Generated by Django 5.0.1 on 2024-01-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerhub', '0005_alter_client_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
