# Generated by Django 5.0.1 on 2024-01-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerhub', '0008_booking_first_name_booking_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='lawyer_first_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='last_name',
            new_name='lawyer_last_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
