# Generated by Django 5.0.1 on 2024-02-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerhub', '0011_alter_feedback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='city',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='role',
        ),
    ]
