# Generated by Django 5.0.1 on 2024-03-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerhub', '0012_remove_administrator_city_remove_administrator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_contact_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
