# Generated by Django 5.0.1 on 2024-03-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerhub', '0013_booking_user_contact_number_booking_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lawyer_contact_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='lawyer_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
